### ISSUE TITLE
Allow for late-binding of references

### ISSUE THREAD

**Issue by mwolfe02** [retailcoder/Rubberduck#114]
In addition to 

    Private Assert As New Rubberduck.AssertClass

which requires a compile-time reference to Rubberduck and deployment of the dll with the mdb, I would also like to be able to do:

    Dim Assert As Object
    Set Assert = CreateObject("Rubberduck.AssertClass")

This would make it easier for developers to add unit-testing (and other Rubberduck functionality) to a project without having to needlessly complicate deployment for functionality that end-users will not see.

**Comment by ckuhn203** [comment]
@mwolfe02  I'm not sure if you're following this issue still, but it has been fixed in the master branch and will be included in the v1.2 release. 

We just needed to declare a `ProgId` for the class.

**Comment by mwolfe02** [comment]
That's great news.  I'll have to play with the v1.2 release.  Keep up the good work.

**Comment by ckuhn203** [comment]
Thanks @mwolfe02. Keep the bug reports coming. =;)-

Also, I've given it some thought and given the tests are stored in modules, rather than classes, you'll need to create a new `AssertClass` in each test method. So, conditional compilation may be the best way to implement what you would like to do.

I've not tested that method, so please let us know how things work out for you.

**Comment by retailcoder** [comment]
@mwolfe02 you may want to follow issue #291 :)
