### ISSUE TITLE
Should Rubberduck.Reflection be allowed to emit VBA code?

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#192]
Allowing that could greatly facilitate VBA stunts like implementing a `Delegate` class that, through the VBE API, can emit code for anonymous methods, and have VBA execute it.

But the VBE API is a security hole, there's a reason why Microsoft Office applications have a macro security setting that enables/disables programmatic access to the VBE object model.

Thoughts?

**Comment by ckuhn203** [comment]
We're already writing code that writes code toVBProjects. I'm not sure I understand. Many planned and implemented features require this.

**Comment by ckuhn203** [comment]
Okay, so [you're talking about exposing an api](http://chat.stackexchange.com/transcript/message/20011209#20011209). I would say yes. We should do this. One of my original goals (that I've strayed away from) was to improve and extend the Microsoft Visual Basic for Application Extensibility (VBIDE) library. This might be a bit tricky to do though. Prior to the public API clean up, I was getting odd errors when I had a reference to both VBIDE and Rubberduck. I'm not sure how to avoid naming conflicts without forcing the client into fully qualifying their calls to Rubberduck and VBIDE. The only thing I can think to do is fully provide access to everything in VBIDE so that references to it are unnecessary.

**Comment by retailcoder** [comment]
Then I would make it a completely separate assembly/.tlb, so users can't inadvertantly enable the reflection API, and IT departments can deem it "unsafe" without ruining all of Rubberduck.

**Comment by ckuhn203** [comment]
Perhaps #158 was closed prematurely then?

If we do this, we'll need to place all of the code that extends VBIDE into that assembly, and reference it from Rubberduck "core". That means the new assembly will need to build before the existing project.

**Comment by retailcoder** [comment]
Hmm.. perhaps we need to have a COM-visible `Rubberduck.Core` assembly with the `Extension` and `DockableWindowHost` classes exposed, then `Rubberduck` (with cherry-picked types made COM-visible) referencing that, and then `Rubberduck.Reflection` referencing `Rubberduck` - the reflection API is nothing more than the `INode` stuff being exposed, and the "dangerous" part of it would be a COM-visible API that can emit (and execute?) VBA code. There is no reason the reflection library couldn't use any of what `Rubberduck` has that's `public`, COM-visible or not.

**Comment by ckuhn203** [comment]
I can't see a good reason to let anybody know about `Extension` and `DockableWindowHost`. What would you possibly do with those classes from a COM client? They're implementation details, not part of the public API. 

It might make sense to expose a `Rubberduck.Reflection` assembly, if that's where we plan to put the parser and the VBIDE extensions, but the "core" would have to reference that assembly, not the other way around. (Hence the quotes, it's not really a "core" because it has outside dependencies.)

**Comment by retailcoder** [comment]
You're right, hadn't realized `Extension` and `DockableWindowHost` were now `_Extension` and `_DockableWindowHost` - no need for a `Rubberduck.Core` then!

But I don't see a reason why VBIDE extensions and/or parser stuff would need to be part of `Rubberduck.Reflection`, it seems completely backwards to me; they *are* at the heart of Rubberduck and completely belong with the "Core" stuff. If `Reflection` needs it, it can just use them... if `Rubberduck.Reflection` references `Rubberduck` :)

**Comment by ckuhn203** [comment]
Adding a link to [this conversation](http://chat.stackexchange.com/rooms/14929/conversation/rubberduck-assemblies-discussion) for posterity.

**Comment by retailcoder** [comment]
Ok. So let's start with exposing an API for client VBA code to be able to iterate project/module members,  leave that within `Rubberduck`, and see where that takes us.

Short, bottom-line answer is "no, ...for now".
