### ISSUE TITLE
Code Explorer could use some sorting and re-instate class icons

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#267]
The Code Explorer used to have class icons for classes, now *everything* has a module icon. I understand we made this sacrifice to speed up the parsing, but it's not as good of a UX as it used to be. It would be nice to differentiate between them. Also, alphabetical sort would be.... awesome. 

![image](https://cloud.githubusercontent.com/assets/2716800/6396356/ee996eaa-bdab-11e4-82a7-f729727d10fa.png)

**Comment by mwolfe02** [comment]
I wholeheartedly agree that the sorting is critical, especially for this to be used as a replacement for the VBA IDE Project Explorer window.

I'd like to propose a couple of other related changes.  These may be better as a separate issue, but I'll put them here for now.  Also, this may be (too) MS Access specific; I'm not as familiar with how the Project Explorer looks in other Office programs simply because I don't spend nearly as much time in them.

Add Grouping Nodes for: 
- Forms
- Reports
- Modules
- Class Modules

This would be similar to what the VBA Project Explorer window does in MS Access, but taking the next step in separating the Forms from the Reports (instead of the catch-all "Microsoft Access Class Objects").

Also, if you separate out the forms and reports, it would be great if you were to chop off the leading "Form_" and "Report_" prefixes.  Besides saving a bit of space, it would allow one to jump to a node by using the first letter of the Form or Report name while another form or report is already selected.

That's a minor annoyance I have had with the VBA IDE for years and I'd love it if you could clean that up.

**Comment by ckuhn203** [comment]
That's a great idea @mwolfe02! I like it. The thought crossed my mind before, but I forgot to write it down. Thank you.

**Comment by retailcoder** [comment]
As of version 1.21, the Code Explorer will look like this:

![image](https://cloud.githubusercontent.com/assets/5751684/6543132/e12ceeb6-c4dd-11e4-9699-465625786317.png)

Double-clicking a folder node will toggle its expanded/collapsed state, and double-clicking anything else will navigate to the corresponding code pane, including module-level nodes, which navigate to L1C1.

**Comment by retailcoder** [comment]
@mwolfe02 all but the prefix-removal has been implemented... and more (follow @rubberduckvba on Twitter or see http://www.rubberduck-vba.com/news.html for all the details!
