### ISSUE TITLE
Target the minimum necessary .Net framework

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#277]
Currently we're targeting the 4.5 framework, which is not supported by Windows XP. We can add support by targeting the 4.0 or 3.5 framework. We need to determine the minimum version necessary and target that instead. Obviously, 3.5 gives us maximum compatibility, but I'm not sure if/what features we're using that wouldn't be available. 

[List of Operating Systems Supported by 4.0 and 3.5](https://msdn.microsoft.com/en-us/library/8z6watww(v=vs.100).aspx).

**Comment by ckuhn203** [comment]
After further investigation, we might not want to target anything older than 4.5. We're using the `async` features that were introduced in 4.5. Sticking with 4.5 means the minimum OS for Rubberduck would be Vista. Considering XP has reached the end of it's lifecycle, I'm not sure we should uproot the code base to support it. On the other hand, there are many users out there still using XP, as evidenced by the user who brought this to our attention. Thoughts @retailcoder?

https://twitter.com/danrfraser/status/572323348866326528/photo/1

**Comment by retailcoder** [comment]
I don't think disabling the TPL & async code for a < 4.5 target would make a good UX. And not leveraging  async/await and the Task Parallel Library means we need to implement multithreaded code ourselves.

Windows XP is out, officially not supported since almost a year now - we know our code can run on a Vista+Office97 setup, I don't think it's worth the effort to go out of our way to retarget for 4.0.

**Comment by ckuhn203** [comment]
Agreed, but I'm going to leave this issue open until we've documented minimum system requirements and adjusted the installer to enforce them.

**Comment by ckuhn203** [comment]
Added info to Wiki & ReadMe. I still need to address the installer.

**Comment by robodude666** [comment]
No possibility of having a less feature-packed version that support XP?

**Comment by ckuhn203** [comment]
No. We rely on `async` features that are only present in 4.5.
We have no plan on supporting Windows XP.

http://windows.microsoft.com/en-us/windows/lifecycle

**Comment by robodude666** [comment]
What about [Microsoft.Bcl.Async](http://www.nuget.org/packages/Microsoft.Bcl.Async/)? From my understanding, if using with VS2012+, it supports Windows XP + .NET 4.0 Client.

**Comment by ckuhn203** [comment]
I would consider looking at a fully functional pull request, but I'm not going to spend my time implementing functionality for a dying OS. So, feel free to fork and add support. If you make it work, we'll pull it into the code base.

**Comment by retailcoder** [comment]
And then what? We target 4.0 and forget all about `async/await`? I strongly oppose this. Part of why I'm enjoying this project is because I can learn new things doing it. Reimplementing the async stuff with pre-4.5 features isn't somewhere I want to go. Next thing you know you need to target 2.0 and drop all LINQ code because some dude wants to use Rubberduck on Win98 in Office 97? No thanks.

**Comment by ckuhn203** [comment]
Like I said @retailcoder , I would absolutely look at pull request that uses the library @robodude666 linked to, but I'm not going to spend my time on it.

**Comment by retailcoder** [comment]
Also, a lot of poor engineers can't download and install VBE add-ins on their office machine, for the same corporate reasons they're stuck on XP...
