### ISSUE TITLE
Project should have a name

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#399]
Per #157, a VBProject that's called `VBAProject` is going to be problematic for the source control feature.

Let's implement an inspection that looks at project names and issues a warning for all projects that have the default `VBAProject` name. Something like..

    declarations.Where(d => d.DeclarationType == DeclarationType.Project 
                         && d.IdentifierName == "VBAProject") // hard-code?

Using the `Declarations` API will return `Declaration` objects that can be directly passed as targets to the *rename* refactoring for an easily implemented quick-fix, so renaming the project will automatically update all in-code references to it.

**Comment by robodude666** [comment]
Is #157 implying that the Repository name that's going to be created will be the same as the Project's name? Why can't they be named independently?

I work with Excel workbooks that interact with 3rd party software that requires the main project to be called VBProject.

**Comment by retailcoder** [comment]
That's a fair point. Besides the rest of the code no longer relies on project names (as of ...yesterday lol), @ckuhn203  thoughts?

**Comment by ckuhn203** [comment]
It is a fair point, but let me explain a bit and see if we can come up with an alternative. 

In an editor like visual studio, the project and the repository are physically the same directory. In VBA, the code is saved along with the host application file. The source control integration works by exporting all of the code to an external directory, which may or may not be in the same location as the host document. Because of this, we need a way to relate the code in the document to its corresponding repository. 

My intent was to use the project name to do this. It made sense at the time, but now I question it. I would still like to automatically discover the repository though. I'd hate to prompt the user for a location when we could be saving it to the config. So, if anyone has suggestions on how that could be done differently, I'm all ears and open to suggestions.

**Comment by Hosch250** [comment]
For that matter, we might as well have a warning that classes are named the default "ClassX".

**Comment by retailcoder** [comment]
Related: #31 *Use Meaningful Names* inspection

**Comment by ckuhn203** [comment]
@Hosch250 @retailcoder I'd still like to hear thoughts about how else I could go about the SC integration in regards to this.

**Comment by robodude666** [comment]
@ckuhn203 I don't see the issue when it comes to source control. Could you please elaborate? Were you expecting to create a folder in the repo with the name of the project and put all source into that folder? If the user wants to leave the project called `VBAProject` let them. If they run into conflicts later because they need to maintain two projects in a single repo then they'll be forced to rename it when they need to.

Like with what @Hosch250 said, and as @retailcoder pointed to #31, there's no problem with warning that you're not using a meaningful name. Same goes for the project name, but it shouldn't be a show stopper. If I want to use Label1, Module1, or VBAProject... why can't I? Maybe I'm just prototyping something and I'll refactor/rename later. Rubberduck shouldn't explode just because I didn't want to use meaningful names from the start.

**Comment by retailcoder** [comment]
`VBProject.Filename` refers to the file name of the Office document that contains the VBA code. Perhaps we can use that path and sanitize the name of the document, create a subfolder with that sanitized name (perhaps suffixed with `.VBA`), and problem solved?

**Comment by ckuhn203** [comment]
@robodude666 right now, when the Source Control panel is first loaded, RD tries to find a repository in the user settings that matches the project that is currently active. For reference, [this is the `IRepository` interface][1] that is used to serialize the data.

    public interface IRepository
    {
        string Name { get; }
        string LocalLocation { get; }
        string RemoteLocation { get; }
    }

Now, when the UI gets loaded, it matches the `VBProject.Name` to the `Repository.Name` to [determine which git repo to connect to][2].

            try
            {
                _provider = new GitProvider(this.VBE.ActiveVBProject, _config.Repositories.First(repo => repo.Name == this.VBE.ActiveVBProject.Name));
            }
            catch (SourceControlException ex)
            {
                //todo: report failure to user and prompt to create or browse
                _provider = new GitProvider(this.VBE.ActiveVBProject);
            }

I find it to be an extremely poor UX to force the user to browse for their working directory every time they open a project and this was the best solution I could come up with. I'm wide open to suggestion about alternative ways to connect a particular Git Repo to a particular VBA Project.

[1]: https://github.com/retailcoder/Rubberduck/blob/sourcecontrol/Rubberduck.SourceControl/IRepository.cs
[2]: https://github.com/retailcoder/Rubberduck/blob/sourcecontrol/RetailCoder.VBE/UI/SourceControl/SourceControlPresenter.cs#L117

**Comment by ckuhn203** [comment]
For the record, I'm not suggesting that any of those other "issues" be a show stopper, but *as currently designed*, not naming your project is a show stopper *if you want to leverage the integrated source control feature*. It would affect just this feature.

**Comment by retailcoder** [comment]
I find requiring the user to save their Office document somewhere is fair enough of a restriction to impose; it would move the problem from `VBProject.Name` to `VBProject.Filename`, and the latter can only be unique on a given computer. The only thing is that you can no longer have a repository for a project that you didn't save somewhere, which I would have no problem with as a user.

**Comment by ckuhn203** [comment]
That sounds fair enough to me. Any suggestions on how to handle a host document being moved?

**Comment by retailcoder** [comment]
If the host document cannot be found, that's when you prompt the user for it :wink:

**Comment by ckuhn203** [comment]
And re-write the existing `sourcecontrol.rubberduck` entry. Sounds like a plan. Definitely worth trying.

**Comment by Hosch250** [comment]
Needs a quick-fix.

**Comment by Hosch250** [comment]
Broken because the IdentiferName for DeclarationType Project only returns VBA.

**Comment by ckuhn203** [comment]
@Hosch250 what's broken? I'm confused. What just happened here?

**Comment by Hosch250** [comment]
@ckuhn203 I don't know - I'm :confused: myself.

**Comment by ckuhn203** [comment]
Lol. Fair enough.
