### ISSUE TITLE
Inspections should default to "Warning"

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#400]
Default severity level for code inspections is pretty much arbitrary.

I think we should have standard defaults:

 - **Error** for code inspections that actually identify/prevent a runtime error (we don't have any at this point)
 - **Suggestion** for *ObsoleteX* inspections
 - **Warning** for everything else

So let's change the default inspection severity to `Warning` for all implemented inspections.

**Comment by Ryankey** [comment]
Is there any merit to having the Obsolete Inspections set to severity 'Suggestion'?

**Comment by retailcoder** [comment]
@Ryankey not really. The severity levels are really just configurable indicators; the only setting that has an actual effect is the `DoNotShow` level, which disables an inspection (and improves inspection performance as a side-effect).

Or are you suggesting (!) the *ObsoleteX* inspections should all default to `Suggestion`?

**Comment by Ryankey** [comment]
@retailcoder Sorry for the confusion, I was suggesting that they be set to default `Suggestion` since I don't feel like they are on the level of a `Warning`. My (made-up) understanding of the `Warning` severity is that it has a chance to cause problems (such as an undeclared or unassigned variable being used). The <i>ObsoleteX</i> inspections, as far as I know, are suggestions to replace deprecated code.

Obviously the user can always override the default severity, but I'd like to make sure the default settings are the "best" that they can be since I'm changing them all anyways.

**Comment by retailcoder** [comment]
Oh, well I don't see a problem with that!

**Comment by retailcoder** [comment]
Side note, I **wish** I could implement an `UndeclaredIdentifierUsageInspection` - but the grammar is picking up *many, many, many* things under the `ambiguousIdentifier` grammar rule, so that's unfortunately not something we can really do without taking a massive performance hit and hard-coding the entire VBA core library identifiers.

**Comment by ckuhn203** [comment]
So, here's something to remember when we release this, because it will confuse the crud out of people. Setting the default only "works" for newly added inspections, or new installs. Once a configuration file exists on the user's machine, RD will *always* use whatever is in the config file. If/When we change the default, it will only affect new users unless they remove the config file from the AppData folder.
