### ISSUE TITLE
"Function '{0}' returns no value" is incorrectly labeled.

### ISSUE THREAD

**Issue by robodude666** [retailcoder/Rubberduck#401]
The Code Inspection item:
```
Function '{0}' returns no value
```
is incorrectly labeled. A datatype will always have a default value. For example, Long = 0, String = Empty, etc. I think the Code Inspection item should be:
```
Function '{0}' returns implicit value
```
with the "fixes" being to either:
* Convert to a Sub if no callers are using it as a function
* Explicitly set a return value

EDIT:

I just realized that the fix _IS_ to convert to a sub, however, it doesn't seem to check if any callers are using it as a function which will cause your other code to break.

**Comment by retailcoder** [comment]
Correct. The wording of that one was annoying me as well; I changed it to say *`Return value for member '{0}' is never assigned`*, which is much clearer I find - I swapped "function" for "member", because that inspection also applies to property getters.

The fix for that one is indeed problematic, especially with MS-Access, which *requires* macro procedures to be `Function` procedures.

If you agree with the new description I gave it, I'll close this issue, as it's already fixed, just not released yet.

**Comment by retailcoder** [comment]
I'll make a separate issue for the "convert to `Sub` procedure" fix; if the *Procedure not used* inspection works without too many false positives, then it shouldn't be too hard to assess whether the function-that-should-be-a-sub is called or not.

I'm not sure about the other suggested fix though - the *Extract Method* refactoring somewhat correctly guesses what the extracted function's return value should be, but it's still up to the user to confirm or manually select another: I wouldn't want to introduce an assignment *automatically*, so letting the user know there's a potential issue with that function seems "good enough", no?

**Comment by robodude666** [comment]
I agree it's "good enough" :smile: Just pointing out the "ideal" fix that something like Resharper would suggest.

**Comment by retailcoder** [comment]
haha I **wish** I could do the magic R# is pulling off!
