### ISSUE TITLE
Format requires a reference

### ISSUE THREAD

**Issue by eteichm** [retailcoder/Rubberduck#418]
Hi 

I'm using Rubberduck v1.22.  
When executed by an end user, the below code requires a missing Rubberduck reference: 
Msgbox "File processed in "  & Format(now - begin, "hh:mm:ss") 
Unchecking the Rubberduck reference solves the issue. 

Does Rubberduck includes a Format function?
If so, how should I call the vba Format function?  
Have I missed something? 

Thanks for this great tool!
Eric

**Comment by ckuhn203** [comment]
I don' t *think* we've exposed any such method in our API, but I'll look into it to make sure I'm not missing something.

In the meantime, you can explicitly reference the standard VBA library to resolve the namespace issue.

    `VBA.Format(now - begin, "hh:mm:ss")`

(Untested, let me know if that works.)

**Comment by retailcoder** [comment]
Indeed, there is no `Format` method in the RD type library.

Adding a test module to your VBA project adds a reference to Rubberduck.tlb
and an early-bound instance of the `AssertClass`, so that you can author
your unit tests with IntelliSense on the `Assert` object.

When you distribute your project to end users, the unit-testing code no
longer needs the early-bound reference, and if end users don't have the
.tlb in their machines your code will produce weird compile errors as
you're experiencing.

@ckuhn203 qualifying the `Format` function will only possibly move the
problem elsewhere, the code will refuse to compile as long as there's an
early-bound `AssertClass` instance in the project.

The solution is to remove the project's reference to Rubberduck.tlb and
late-bind the `AssertClass` instance in the test modules, like this:

    Private Assert As Object

The late-binding needs to be done in the *ModuleInitialize* procedure, like
this:

    '@ModuleInitialize
    Public Sub ModuleInitialize()
        Set Assert = CreateObject("Rubberduck.AssertClass")
    End Sub

And then the *ModuleCleanup* procedure can destroy the instance:

    '@ModuleCleanup
    Public Sub ModuleCleanup()
        Set Assert = Nothing
    End Sub

This way the unit tests can still run on a machine that has RD installed,
and the VBA project will compile on a machine that doesn't have it.

**Comment by ckuhn203** [comment]
Another option is to export and remove your test modules from the project prior to release.

**Comment by retailcoder** [comment]
@ckuhn203 not really. You'd still have to remove the RD reference, and exporting/re-importing the test modules would be a pain in the neck. We've made sure `AssertClass` could be late-bound *specifically* for this.

**Comment by retailcoder** [comment]
I'm closing this issue; #291 is closely related to this.

**Comment by eteichm** [comment]
@retailcoder Thanks for the detailed answer. 
I'll test it.
