### ISSUE TITLE
Renaming variables breaks functions/subs with variable declarations on multiple lines

### ISSUE THREAD

**Issue by rossorp** [retailcoder/Rubberduck#446]
Take a Sub (or Function) such as the following, with multiple arguments split across multiple lines:
```vba
Public Sub Foo(ByVal Var1 As Integer, _
               ByVal Var2 As Integer)
    
    Debug.Print Var1
    Debug.Print Var2
    
End Sub
```
If `Var1` is renamed to `Var3` using Refactor -> Rename, it results in the following:
```vba
Public Sub Foo(ByVal Var3 As Integer, ByVal Var2 As Integer)
               ByVal Var2 As Integer)

    Debug.Print Var3
    Debug.Print Var2
    
End Sub
```
As can be seen, it correctly renames the target variable, however it condenses the Sub/Function declaration to a single line, but does not remove the additional lines from the previous multi-line declaration, resulting in a syntax error.

**Comment by retailcoder** [comment]
Thanks for your feedback! Our VBA grammar has a number of limitations: numbered lines, comments, nested conditional compilation statements, ... and line continuations are a problem.

More specifically, the parser doesn't even see the line continuations. Since we're using a `TokenStreamRewriter` to actually perform the renaming, this issue may be very hard to fix without addressing the grammar issue with line continuations.

But it might not be impossible either. This is a very interesting bug.

**Comment by retailcoder** [comment]
I'm pretty sure there's an [extremely] easy fix for that one, but it involves rewriting the multiline signature on one line.

Would that work for you? The idea is to avoid breaking the code at all costs.

**Comment by retailcoder** [comment]
I'll go for the easy fix until the grammar understands continued lines.

**Comment by rossorp** [comment]
Leaving it as it is (ie. multi-line) would be nice, but certainly not an necessity I don't think. Rewriting to a single line is fine - as you say, as long as code doesn't get broken.

**Comment by Hosch250** [comment]
This is now fixed in my latest commit, with a single-line declaration.
