### ISSUE TITLE
Update rubberduck-vba.com

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#575]
Our official website hasn't been updated in ages. Let's revamp the whole thing and launch a new design together with the new version.

Any suggestions?

(yes, I'm considering putting the nav at the top like a *normal* website)

**Comment by ckuhn203** [comment]
We kind of have a lot going on in the way of our web presence. We have Rubberduck News, the home page, and the wiki. It'd be nice to really make the website our "other hub" (sorry, bad github pun). 

Maybe we can find a way to better embed Rubberduck News posts into the website and start centralizing our documentation on the website instead of the wiki. Thoughts?

**Comment by retailcoder** [comment]
I would like the GitHub wiki to he the "dev hub" where we document the code and COM API's, and the website to be the "user's hub" where we document the features and, basically, how to use Rubberduck.

Rubberduck News deserve more space indeed.

**Comment by Hosch250** [comment]
Completed, will roll out with 1.4.

**Comment by retailcoder** [comment]
All pages redone, features page is tremendously more detailed... and yet still only offers an overview. I think the simplest would be to create a wiki section dedicated to *using* each feature; the screenshots on the website could link to these wiki pages.
